### ISSUE TITLE
About the NUS_WIDE

### ISSUE THREAD

**Issue by mengliu1991** [kunhe/TALR#1]
Hi,

In the AllLables81.txt, each row contains 162 labels, I wanna to know why not 81 elements?
How these 162 elements {0,1} denote?

**Comment by daisystar** [comment]
> Hi,
> In the AllLables81.txt, each row contains 162 labels, I wanna to know why not 81 elements?
> How these 162 elements {0,1} denote?

hi, have you downloaded the original pictures of nuswide?The download link given by the author is invalid. Thank you very much

**Comment by Mdahao** [comment]
> Hi,
> 
> In the AllLables81.txt, each row contains 162 labels, I wanna to know why not 81 elements?
> How these 162 elements {0,1} denote?

have you downloaded the original pictures of nuswide?
